### ISSUE TITLE
Test fails when installing Joi from a location other than hapijs/joi.

### ISSUE THREAD

**Issue by nallenscott** [hapijs/h2o2#10]
h2o2 v4.0.0 passes all tests when installing Joi from hapijs/joi, e.g. `"joi": "5.x.x"`:

![screen shot 2015-04-08 at 3 50 25 pm](https://cloud.githubusercontent.com/assets/11765848/7053939/0fd1acec-de07-11e4-9b91-db18886959b3.png)

---

h2o2 v4.0.0 fails a test when installing Joi from another location, e.g. `"joi": "nallenscott/joi"`. In the failed scenarios, Joi is an unchanged fork or local copy:

![screen shot 2015-04-08 at 4 04 37 pm](https://cloud.githubusercontent.com/assets/11765848/7054213/0e60b4d2-de09-11e4-95c3-74a03de20231.png)

**Comment by Marsup** [comment]
Indeed your fork is a 6.1.0.
