### ISSUE TITLE
how to proxy SSE  event-stream requests ?

### ISSUE THREAD

**Issue by allaf** [hapijs/h2o2#107]
#### 
* *environment* : node
#### 
I have a node app that uses hapi and h2o2 and I want it to proxy GET requests (coming from the browser) to a sse service.

I tried just `proxy` and `passThrough: true` and let it handle everything but it doesn't work.
The request is never solved and keeps a pending state.

```js

server.route({
    method: 'GET',
    path: '/sse',
    handler: {
        proxy: {
            passThrough: true,
            mapUri: request => ({uri: `http://localhost/sse-service`})
        }
    }
});
```

 also tried with  : 
```js
options: {
      payload: {
        output: 'stream',
        parse: false,
      },
```
but it doesn't work either.

thx for your help

**Comment by allaf** [comment]
up

**Comment by hueniverse** [comment]
Unfortunately, no community resources were available to help resolve this issue after two weeks, and it is being closed. We close unresolved community issues to keep the issue tracker organized and effective. Please check https://hapi.dev/support for other support options.
