### ISSUE TITLE
Add validation to the request payload

### ISSUE THREAD

**Issue by abhagupta** [hapijs/h2o2#115]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 
* *module version*: 
* *environment* (e.g. node, browser, native): 
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*:

#### What problem are you trying to solve?
An option to validate the request payload with a schema provided.  It will be nice to have some level of validation even if this is used as thin proxy

**Comment by hueniverse** [comment]
You can set any validation rules you want on the route like any other route.
