### ISSUE TITLE
Proxy validation allows invalid combination of keys.

### ISSUE THREAD

**Issue by antony** [hapijs/h2o2#116]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): 

Community

* *is this issue currently blocking your project?* (yes/no):

No

* *is this issue affecting a production system?* (yes/no):

No

#### Context

* *node version*: 13.5.0
* *module version with issue*: 9.0.1
* *last module version without issue*: 9.0.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapda/hapi
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

The documentation states that you can't combine `onResponse` and `uri`. However, if you do, you are not warned.

This differs to combining `mapUri` and `uri` which causes a validation error.

The net result is you can end up with config which doesn't work, and doesn't error.

```js
const route = {
  method: 'GET',
  path: '/support/{param*}',
  handler: {
    proxy: {
      onResponse: function (err, res, request, h, settings, ttl) {
        ...
      },
      uri: 'https://example.com/{param}'
    }
  }
}
```

#### What was the result you got?

No error

#### What result did you expect?

A validation error to let me know I can't combine `uri` + `onResponse`

**Comment by hueniverse** [comment]
It is not about `onResponse` and `uri` but about the combination of `onResponse`, `mapUri`, and `uri`. It is listed in a specific section, not in the options definitions.
