### ISSUE TITLE
httpClient type not yet present in @types/hapi__h2o2?

### ISSUE THREAD

**Issue by aancer-rca** [hapijs/h2o2#118]
#### Context

* *node version*: 12.16.2
* *module version*: `"@hapi/h2o2": 9.0.1` with  `"@hapi/hapi": "^19.1.1"`
* *environment*: node
* *used with*: Hapi framework, TypeScript

#### How can we help?

Hi,
I'm trying to use the httpClient within hapi's h2o2 proxyHandler. However, I'm noticing that the httpClient type is not present in the @types/hapi__h2o2 package at https://www.npmjs.com/package/@types/hapi__h2o2 on interface _ProxyHandlerOptions_. 
The types version is listed at a latest version of 8.3.1 so this is understandable. 
However, please advise if/ when this type will be added?

Relates to #93

**Comment by hueniverse** [comment]
You need to open this issue in the @types repo.
