### ISSUE TITLE
Pass `h` or similar to `mapUri` and `onRequest` for server settings/configuration access

### ISSUE THREAD

**Issue by brianjmiller** [hapijs/h2o2#123]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v14.15.1
* *module version*: 9.0.2
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*:

#### What problem are you trying to solve?

I would like to be able to store configurable values such as "host", "port", "path", etc. within the Hapi server configuration and then be able to leverage them from within the `mapUri` and `onRequest` functions. These two functions are called within the handler for the route and it appears straightforward to pass the `h` through to them. They currently receive the Wreck request which AFAICT doesn't provide a reference to the app level configuration.

I'm open to better solutions of how to provide configurable values to these handlers, whether that is through the plugin interface or some such. Obviously I can work around it by using a singleton or similar at the global level but I'd rather pass them through the Hapi server in some way as that is my understanding of the proper way to do things of this nature in Hapi.

#### Do you have a new or modified API suggestion to solve the problem?

It seems sufficient to pass `h` as the second argument in the call on https://github.com/hapijs/h2o2/blob/master/lib/index.js#L94 and https://github.com/hapijs/h2o2/blob/master/lib/index.js#L167

**Comment by brianjmiller** [comment]
Seems https://github.com/hapijs/h2o2/issues/89 is a duplicate, but was requested for a different reason. As mentioned I don't necessarily need all of `h` it just seemed the obvious place to start.

**Comment by Nargonath** [comment]
> They currently receive the Wreck request which AFAICT doesn't provide a reference to the app level configuration.

From what I can see [here](https://github.com/hapijs/h2o2/blob/bae468bc66ab18608d2c1f9c1a7291f4e830d146/lib/index.js#L92) the request object is the one from hapi and not Wreck. This function is an handler body as you'd do it when developing your own endpoint. If you add values to `server.app` you should be able to retrieve them in `mapUri` through `request.app`.

Regarding `onRequest` it does indeed only get passed the `request` object from Wreck. As @kanongil answered in the issue you linked I don't think there is a point to pass the whole response toolkit to `onRequest` since it's called when performing the request to the upstream server. Perhaps we could at least pass along the original `request` object. Could you detail a bit more your use case why you'd need to access your app level configuration in `onRequest`?

**Comment by brianjmiller** [comment]
Thanks for the response. I'm not sure why I conflated the request to `mapUri` and to `onRequest` as both being Wreck requests. Your comment helped me to understand the overall flow better. I also don't know why my output for trying to see the values from `request.app` didn't work as trying again this morning I'm able to pull the config from `request.server.app` that I need in `mapUri`.

I think ultimately my need for the values in `onRequest` is better fulfilled by using a `pre` lifecycle method, I just wasn't thinking about the overall event flow correctly. IOW shifting the work to before the proxy is even considered is a better route than after the new proxy request is created.

Sorry, for the noise, but I do appreciate your help, thanks!

**Comment by Nargonath** [comment]
You're welcome. I'm glad I could help you.

> I'm able to pull the config from request.server.app that I need in mapUri

Be aware that `request.server.app` is read-only whereas `request.app` is read/write: https://hapi.dev/api/?v=20.0.3#-requestapp

**Comment by kanongil** [comment]
`request.server.app` is read/write as well, but you can't use it to store request-specific state.

**Comment by Nargonath** [comment]
I based my explanation on the documentation on the website: https://hapi.dev/api/?v=20.0.3#-requestserver. Is it the server object itself that is read-only but the property `app` is not or just an error in the documentation?

**Comment by Nargonath** [comment]
I took a look at the codebase and you're right, it seems that the `request.server` object is not truly read-only. Does it mean the documentation is just to stir people away from modifying `request.server.app` from their handler or other method accessing the `request` object without technically enforcing it?
