### ISSUE TITLE
How to make load balancing proxy ?

### ISSUE THREAD

**Issue by akdj** [hapijs/h2o2#126]
Hi 
I'm using hapi with H2O2 to implement a  Nodejs proxy service that redirect some specific requests to another service, but I don't know how to make it load balancing. Is it possible de make it with H2O2 plugin?

**Comment by devinivy** [comment]
That's an interesting question.  It's not specifically a feature of h2o2, but I think you could achieve it.  One way you might approach is this using the [`mapUri`](https://hapi.dev/module/h2o2/api/?v=9.0.2#using-the-mapuri-and-onresponse-options) option to choose a host from a list for each request.

**Comment by Nargonath** [comment]
You'll have to develop yourself the whole logic though: selection algorithm (round-robin or whatnot), determining which host is suitable for traffic load etc. IMO you'd better be using a dedicated tool for that such as [Traefik](https://doc.traefik.io/traefik/routing/overview/).
