### ISSUE TITLE
some options are not defined in typescript 

### ISSUE THREAD

**Issue by akdj** [hapijs/h2o2#129]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v16.6.2
* *module version*: 9.1.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*:

#### What problem are you trying to solve?
Some options like httpClient is not defined in the typescript model.

#### Do you have a new or modified API suggestion to solve the problem?
Could you please make an update of [@types/hapi_h2o2] ?(https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/h2o2/)

**Comment by kanongil** [comment]
Hapi does not provide types for h2o2, or control the quality. You need to reach out to DT.

**Comment by akdj** [comment]
ok, thank you
