### ISSUE TITLE
Incorrect handling of http to https redirects

### ISSUE THREAD

**Issue by dominykas** [hapijs/h2o2#13]
I'm still debuging this, but here's what I know so far:

* I have a thing that proxies to `http://drive.google.com/uc?id=xxx`, which in turn redirects to an https URL.
* It used to work with hapi@8.6
* It doesn't work with hapi@8.8
* It works if I proxy to `https://drive.google.com/uc?id=xxx`
* Under node 0.10 the error message is `Client request error: socket hang up`, under node 0.12 the message is `Uncaught error: Protocol "https:" not supported. Expected "http:".`.

Hapi 8.6 uses:
```
h2o2@4.0.1
wreck@5.5.1
```

Hapi 8.8 uses:
```
h2o2@4.0.1
    wreck@5.6.1
wreck@6.0.0
```

I can make things work if:
* I comment out the line, that sets `internal.agent` in h2o2: https://github.com/hapijs/h2o2/blob/master/lib/index.js#L93
* ~~I downgrade to wreck@5.5 in both - h2o2 and hapi (I'm not sure how the two get intermixed, but if I downgrade only under h2o2 - it doesn't work... also if both have 5.6 or 6.0 - it doesn't work)~~ No longer sure about this.

**Comment by dominykas** [comment]
In the end, could it after all be a bug in wreck, probably related to something here: https://github.com/hapijs/wreck/pull/85?

**Comment by dominykas** [comment]
End-to-end test: https://gist.github.com/dominykas/2433d5c9e9fb941c52d5

Result: 500
Expected: the image from wherever http://drive.google.com/uc?id=0B56OaK7BeVZ7ZU1pZkQtQ2R4dU0 redirects to

**Comment by hueniverse** [comment]
@geek ?

**Comment by geek** [comment]
@dominykas does this look like the correct test case: https://github.com/hapijs/wreck/pull/99

**Comment by dominykas** [comment]
Roughly looks like it, but I'd guess it doesn't fail, does it? h2o2 uses a custom `agent` somewhere in the options - I think that's related.

**Comment by geek** [comment]
@dominykas thanks, you are right about it not failing.  Let me try with a custom agent.

**Comment by cudasteve** [comment]
Any update?  I think I might be hitting a similar issue with Hapi 8.8.

**Comment by osukaa** [comment]
@cudasteve I released the new version of h2o2 (4.0.2) a couple of days ago with the new version of wreck.

**Comment by cudasteve** [comment]
Thanks.  My issue turned out to be something else.

**Comment by nathanmarks** [comment]
@dominykas Did you ever debug this this? I'm having exactly the same issue, latest version of h2o2.

**Comment by ihorskyi** [comment]
Same issue here

**Comment by jonsherrard** [comment]
If you get this issue. Log out the URL you're passing into the proxy handler. 99 times out of 100 your URL isn't correct, a missing `:` in the protocol, or an undefined `var/const` in the URL  you've buit up. Hope that helps someone!
