### ISSUE TITLE
How to change response headers

### ISSUE THREAD

**Issue by kevinsimper** [hapijs/h2o2#14]
Normally when you `reply(json)`, you can do `.header(key, value)` afterwards.

How can you change headers, if you respond with a `return reply.proxy()`?

Because `return reply.proxy({}).header(key, value)` does not work.

**Comment by jaw187** [comment]
@kevinsimper you can manipulate the headers in the `onResponse` function via `res.headers`.

**Comment by kevinsimper** [comment]
@jaw187 Thank you!
