### ISSUE TITLE
Document reply.proxy

### ISSUE THREAD

**Issue by hueniverse** [hapijs/h2o2#15]
### `reply.proxy(options)`

Proxies the request to an upstream endpoint where:
- `options` - an object including the same keys and restrictions defined by the
 [route `proxy` handler options](#route.config.proxy).

No return value.

The [response flow control rules](#flow-control) **do not** apply.

```js
var handler = function (request, reply) {

    return reply.proxy({ host: 'example.com', port: 80, protocol: 'http' });
};
```

**Comment by osukaa** [comment]
Do I add this to the README?

**Comment by hueniverse** [comment]
Yep.
