### ISSUE TITLE
sending query parameters through 

### ISSUE THREAD

**Issue by chacliff** [hapijs/h2o2#23]
can  you explain how to proxy query parameters, or is this not supported functionality. i have passthrough: true and i'm using  mapURI 

`
method: ['POST','GET', 'DELETE'], path:'/jaya/{p*}', handler: {
		proxy: {
			passThrough: true,
			mapUri: function(request, callback){
				if(request.params.p)
					callback(null, 'http://localhost:82/' + request.params.p);
				else
					callback(null, 'http://localhost:82/');
			}
		}
	}
},
`

**Comment by osukaa** [comment]
The passthrough options is for the headers. You could do something like I'm going to write next, but you could use the property `request.path` from the request object -> http://hapijs.com/api#request-object

```
method: ['POST','GET', 'DELETE'], 
path:'/jaya/{p*}',
handler: { 
    proxy: { 
        passThrough: true, 
        mapUri: function(request, callback){ 
            if (request.) 
                callback(null, 'http://localhost:82/' + request.path);
            else callback(null, 'http://localhost:82/'); 
}
} 
} 
}, 
```

**Comment by chacliff** [comment]
i did try to use request.path. apparently query parameters don't come with hapi, what i ended up doing was request.url, which as a "search" key for query parameters which is still in the form of 

`?<key>=<value>&<key>=<value` 

I was just under the impression that this would be part of the built in functionality of a "proxy"

**Comment by osukaa** [comment]
You could try using qs and stringifying the array of params https://www.npmjs.com/package/qs

**Comment by dylancwood** [comment]
The Hapi request object has a `query` property, which you can also pass `querystring.stringify()` to get the query string:

```js
...
mapUri: (request, callback) => {
    const newUrl = modifyUrl(request.url);
    newUrl.query = request.query || {};
    callback(url.format(newUrl));
}
```
Since the querystring is part of the URI, it makes sense that the `mapUri` function should need to explicitly set the querystring.

**Comment by arb** [comment]
You should be able to get the raw query string from `request.raw`. I think it'll be under `request.raw.search`. This is a good option if you don't need to change the query string, then you don't need to try to stringify or reformat it again.

**Comment by chacliff** [comment]
yep thanks guys for the help, as i was trying to allude it would be nice if it was a feature of the plugin since you can specify whether or not to include the header in the options. 
something like 

`server.route({
    method: 'GET',
    path: '/',
    handler: {
        proxy: {
            host: '10.33.33.1',
            port: '443',
            protocol: 'https',
            passthrough: true,
            includeQuery: true 
        }
    }
});`

**Comment by pushred** [comment]
It's actually in `request.url.search` for anyone else who stumbles here later.

**Comment by danielo515** [comment]
Pleas help me clarify with this,  there is no way to pass query params at the same time that you rewrite the path ?
I'm talking about something as simple as this:

```js
handler:
        {
            proxy: {
                passThrough: true,
                uri: `${BASE_URL}/results/{paramOne}/{paramTwo}`
            }
        }
    
```

As @chacliff said, I expected this kind of basic functionality on a proxy
