### ISSUE TITLE
Cannot proxy if payload is parsed

### ISSUE THREAD

**Issue by danielb2** [hapijs/h2o2#26]
``` javascript
 plugin.route({
     method: 'POST',
     path: '/item',
     handler: function (request, reply) {

         reply.proxy({ host: 'www.google.com', port: 80 });
     }
 });
```

results in an error: Cannot proxy if payload is parsed or if output is not stream or data

While:

``` javascript
   plugin.route({
       method: 'POST',
       path: '/item',
       handler: {
           proxy: {
               host: 'www.google.com', port: 80
           }
       }
   });
```
works as expected.

Is the former really considered as parsing payload?

https://github.com/hapijs/h2o2/blob/master/lib/index.js#L71

`route.settings.payload` in this context shows up as `null`

**Comment by danielb2** [comment]
I suppose it has to be because the payload _could_ be manipulated?

**Comment by danielb2** [comment]
I've thought about this some more. it seems like this should be able to be done. Looking forward to comments

**Comment by danielb2** [comment]
` config: { payload: { parse: false } }` as a route option is necessary :/

**Comment by nico-onmap** [comment]
I am having the same problem. Adding config/payload isn't an option since I want to handle both POST/GET methods and there's no payload option in GET.

Must I duplicate my route and add the config option or is there a cleaner way to resolve this?
