### ISSUE TITLE
Flow control rules link is broken

### ISSUE THREAD

**Issue by gergoerdosi** [hapijs/h2o2#27]
In the `reply.proxy()` section: https://github.com/hapijs/h2o2#replyproxyoptions. I don't know where it is supposed to point, so just taking a note here.

**Comment by mtharrison** [comment]
Not sure but maybe here: https://github.com/hapijs/hapi/blob/master/API.md#flow-control

**Comment by sholladay** [comment]
When this gets fixed, I would appreciate some clarification. So those rules do not apply... what rules do apply? My assumption is that the upstream request/response cycle is initiated immediately, since `reply.proxy()` has no return value.

**Comment by osukaa** [comment]
@gergoerdosi I'm sorry the mistake was to take the documentation from the hapijs doc markdown. I'll fix it! And yes, it's the link that @mtharrison mentioned. And @sholladay you're right.

**Comment by sholladay** [comment]
Another way to phrase it: the docs currently say what __isn't__ happening, rather than what _is_. Thus, they are quite vague.
