### ISSUE TITLE
passing back headers after onResponse

### ISSUE THREAD

**Issue by danielb2** [hapijs/h2o2#30]
in the example for onResponse, we show some potential payload manipulation/logging after doing a Wreck.read.  However, what's not apparent in this example is that all the headers in the original response are lost and only the payload is passed on.

I've tried doing res.payload = payload and doing reply(res) which would have been very handy.

If only logging is done, then it's possible to do:

``` javascript
onResponse: function (res, ....) {
   reply(res);
   Wreck.read(res, payload) {
      // loggging can be done on payload
      return;
   }
}
```

( thanks @arb  for thinking of this )

However, as soon as payload manipulation needs to be done, headers need to be copied. Is there a quick way to copy the headers here?

Perhaps the docs should note that in the onResponse example, the headers are lost.

**Comment by osukaa** [comment]
I'm not sure I'm following you with this. The original response comes in the `res` parameter of the `onResponse` callback. You could copy the headers from there.

**Comment by danielb2** [comment]
copying the headers is a  chore, and it's not mentioned in the documentation that the headers is lost when following the instructions for onResponse.

you'd basically have to iterate over all the res.headers and set them one by one. Also, the cookie header is an array and I believe would have to be treated separately.

**Comment by osukaa** [comment]
I agree with you that the documentation should say that headers are lost. Besides that, you could try something like this

```
onResponse: function (err, res, request, reply, settings, ttl) {

    console.log('receiving the response from the upstream.');
    Wreck.read(res, { json: true }, function (err, payload) {

        reply(payload).headers = Hoek.clone(res.headers);
    });
}
```

**Comment by danielb2** [comment]
maybe just include `reply(payload).headers = Hoek.clone(res.headers);` in the read me ? Is the `clone` part necessary?

**Comment by danielb2** [comment]
btw, `reply(payload).headers = res.headers)`
worked great. dunno why I thought anything more complicated would be needed

**Comment by osukaa** [comment]
Cool! I'll update the documentation with the line `reply(payload).headers = res.headers)`

**Comment by sholladay** [comment]
> `reply(payload).headers = res.headers)` worked great

FYI, @hueniverse advised me [not to do this](https://github.com/hapijs/hapi/issues/3096#issuecomment-200696164). I'm not 100% clear on why, but I know that the `header()` function does some processing and may have a meaningful impact here.

It doesn't feel very well thought out.

**Comment by osukaa** [comment]
I'm not sure what would be the best approach for this :/

**Comment by danielb2** [comment]
@hueniverse any thoughts?

**Comment by hueniverse** [comment]
Why not add the headers one at a time with a proper `header()` call?

**Comment by danielb2** [comment]
What's the problem with this approach?

**Comment by sholladay** [comment]
> Why not add the headers one at a time with a proper header() call?

From the `header()` docs, `override` and `duplicate` both default to `true`. But `duplicate` "does not apply" for `Set-Cookie`. It _sounds_ like it won't apply multiple `Set-Cookie` headers correctly, although I have not actually tested this particular case yet.

**Comment by hueniverse** [comment]
There cannot be multiple set-cookie headers. The value would be an array.

**Comment by DevSide** [comment]
Personally, I mutate res.headers

```js
onResponse(error, res) {
  res.headers['Content-Type'] = 'application/json'
  return res
}
```
