### ISSUE TITLE
Accessing body POST parameters in proxy handler

### ISSUE THREAD

**Issue by peacechen** [hapijs/h2o2#33]
Goal: On some routes, the POST parameters need to be modified before they are forwarded.  I can access query parameters (e.g. ?param1=x&param2=y) but I haven't been able to find where the in-body POST parameters are.  Here's what I have that manipulates the query params:

```
server.route({
	method: "POST",
	path: "/myEndpoint",
	handler: {
        proxy: {
            mapUri: function (request, callback) {
                request.query.id = "Some new ID";

                // request.params is empty
                // request.payload doesn't appear to have the POST parameters

                // Call proxied host with modified query parameters.
                // Would prefer to send parameters in body instead of url.
                callback(null, "http://proxiedHost" + request.path + "?" + qs.stringify(request.query));
            }
        }
    }
});

```

How may I access and manipulate the body POST parameters?

**Comment by mtharrison** [comment]
Related issue: https://github.com/hapijs/h2o2/issues/22

h2o2 doesn't buffer/parse the incoming payload so you'd have to do it yourself. Seems kind of inefficient though for a proxy though. If you can get away with encoding the info you need to make the URI decision in the HTTP head, that would be preferable.

**Comment by peacechen** [comment]
Thanks for pointing out the performance hit when processing the payload.  In this application, efficiency isn't a primary concern because the calls are infrequent. 
If I do decide to process the payload, how do you recommend doing so?  I looked into using Wreck but the examples show it taking the response object (not the request object).

**Comment by mtharrison** [comment]
hapi will parse your payload by default when using normal handler function (`function (request, reply) { ... }`). 

Just build up your URI from whatever you need in `request.payload` and then use Wreck to make a new request using that URI and pass along all the headers, payload etc from the original request. Then send the response from Wreck to the client using `reply()`.

This is what h2o2 is doing now (with some extra options) so have a look at the code from here: https://github.com/hapijs/h2o2/blob/master/lib/index.js

**Comment by osukaa** [comment]
Thanks for answering @mtharrison and I agree with his answer
