### ISSUE TITLE
Any way to integrate with catbox?

### ISSUE THREAD

**Issue by EyePulp** [hapijs/h2o2#35]
I'd like to be able cache (via catbox-redis) our proxied content.  I don't see a way to short-circuit the proxy route handler though.  Right now I'm using mapUri and onResponse, as we do a lot of manipulation to the proxied content.

Any suggestions?

**Comment by EyePulp** [comment]
Closing - the lack of response tells me this probably isn't in the cards for h2o2 - just went ahead and built a plugin w/ node-request to get the control needed.

**Comment by jgallen23** [comment]
@EyePulp how did you end up handling this?

**Comment by EyePulp** [comment]
@jgallen23  I built a plain old hapijs plugin and used `node-request` (versus `Wreck`)  that does the proxying.  It was going to be a lot more work to move h2o2 in the direction I needed than to just build it directly.  The nice thing is I can add logic like only caching `200` responses, etc.
