### ISSUE TITLE
Options pass through for Wreck

### ISSUE THREAD

**Issue by nathanmarks** [hapijs/h2o2#36]
Would it be possible to add the ability to pass options to the underlying `Wreck` module carte blanche?

**Comment by osukaa** [comment]
I think it could break the idea of a simple proxying plugin

**Comment by nathanmarks** [comment]
@osukaa Would you be more open to adding more options on a case by case basis? For example, `beforeRedirect` is a useful option in `Wreck` when proxying.

**Comment by spanditcaa** [comment]
@osukaa I'm interested in something like this as well, to enforce TLS method and cipher settings.  As opposed to per request, this type of setting could be applied at plugin registration.  If that is acceptable I can work on a PR.

**Comment by osukaa** [comment]
@spanditcaa yes, please go ahead and make a PR! :)

**Comment by spanditcaa** [comment]
@osukaa - done in https://github.com/hapijs/h2o2/pull/57

**Comment by spanditcaa** [comment]
Closing - specific passthrough features will be supported on a case by case basis.  Please open a PR if any additional option is desired.
