### ISSUE TITLE
How to add auth to the destination?

### ISSUE THREAD

**Issue by jdarling** [hapijs/h2o2#53]
How do you apply authorization to the outbound call?  For Basic Auth could use mapUri, but for other authorization types this seems to be overlooked (at least in the docs).

**Comment by osukaa** [comment]
You would have to generate the token through other means (Bearer token, for example) and add it through the `mapUri`, think like [bell](https://github.com/hapijs/bell) exposes the `request.auth.isAuthenticated`.

**Comment by spanditcaa** [comment]
+1, answered.
