### ISSUE TITLE
how can i get the request.payload in onResponse

### ISSUE THREAD

**Issue by xycloud** [hapijs/h2o2#55]
I wanna get the parsed post payload in onResponse by below: 

```
onResponse: function (err, response, request, reply) {
    console.log(request.payload);
}
```

but which is not the real post params, how can I get that in onResponse

**Comment by osukaa** [comment]
I don't understand your question, the original request is the `request` parameter, so the `request.payload` was the send POST body sent before proxying to an upstream server

**Comment by spanditcaa** [comment]
answered.

**Comment by xycloud** [comment]
em.. i do some hack, close this issue
