### ISSUE TITLE
Default options do not apply when using reply.proxy(options)

### ISSUE THREAD

**Issue by danielo515** [hapijs/h2o2#58]
Hello,

I noticed that when you use `reply.proxy(options)` to proxy request, the options set when registering the plugin do not apply.

Here is how I register the plugin:

```js
        // PROXY
        {
            plugin: {
                register: 'h2o2',
                options: {
                    passThrough: true,
                    protocol: 'http'
                }
            }
        },
```

And here is how I use it 

```js
handler(request,reply){

            reply.proxy( {
                passThrough: true,
                uri: `${RESULTS_SERVICE}/results/{definitionSource}/{program}${request.url.search}`
            } );
        }
```

The settings apply if I use the `handler: { proxy : {} }` form.
Can the default options be applied also to the reply.proxy method? Is a bit uncomfortable to define all the default options again and again on every proxy request.

Thanks and regards

**Comment by osukaa** [comment]
Yes, we had a PR to solve this merged recently! https://github.com/hapijs/h2o2/pull/57. I haven't released a version, which I'm doing later today! That will fix your problem

**Comment by osukaa** [comment]
Version 6.0.1 has been published, your problem should be fixed now!

**Comment by danielo515** [comment]
Cool! I just put on production today my app, but I'll upgrade as soon as possible and test it out.
Thank you very much!

**Comment by spanditcaa** [comment]
@osukaa I don't see 6.0.1 on npm - can you confirm ?

**Comment by osukaa** [comment]
@spanditcaa hey it's now published! https://www.npmjs.com/package/h2o2 I didn't realized I published to the internal registry of the company I work for! Everything is fixed now
