### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by hueniverse** [hapijs/h2o2#61]
This module needs a new maintainer to keep it up to hapi.js standards.

**Comment by spanditcaa** [comment]
@hueniverse I'm happy to help.

**Comment by hueniverse** [comment]
@osukaa Still want to maintain it? It needs some attention...

**Comment by osukaa** [comment]
I don't have enough time as before! If @spanditcaa is up for it, I'll let him :)

**Comment by hueniverse** [comment]
@spanditcaa you can start by reviewing PR and commenting on issues. Once you get going and ready to merge code and publish, we can get you the permissions needed and make it official.

@osukaa thanks for leading this - greatly appreciate the contribution!

**Comment by spanditcaa** [comment]
All reviewed @hueniverse and we can close most of the other current issues (commented in each).

**Comment by hueniverse** [comment]
@spanditcaa you should have the permissions to take over, update the readme and close/merge issues. When you are ready to publish, lmk your npm account.

**Comment by spanditcaa** [comment]
Thanks @hueniverse -- I'm sanpan on npm.

**Comment by hueniverse** [comment]
@spanditcaa done.
