### ISSUE TITLE
hapi v17 support

### ISSUE THREAD

**Issue by hueniverse** [hapijs/h2o2#62]

**Comment by jessie-codes** [comment]
I'll take a stab at getting this to work with the new version and getting a PR in over the next couple days.

**Comment by hueniverse** [comment]
@jessie-codes Great!

**Comment by Samueljoli** [comment]
Heyy @jessie-codes I actually just opened a PR for this now. I too took a stab at this as an exercise to familiarize myself with the breaking changes of hapiv17 and didn't initially intend on opening a PR, buttt it turned out to not be soo bad. Sorry if I'm stepping your toes.

**Comment by spanditcaa** [comment]
merged.
