### ISSUE TITLE
mapUri mis-setting server name for SNI

### ISSUE THREAD

**Issue by BertHartm** [hapijs/h2o2#65]
We're using h2o2 to act as a reverse proxy and forward some requests, but we found we needed to filter out some headers on the request, so we moved from the `uri` parameter to the `mapUri` parameter.

After pulling out the packet sniffer, it seems like when we switch to `mapUri`, the request is being made with `localhost` as the server name during the TLS setup / SNI stage. This does not appear to be happening when we use the `uri` parameter (in fact, we seem to get the correct server name then), despite passing in the same information.

**Comment by spanditcaa** [comment]
@BertHartm can you post a sample repro ?

**Comment by spanditcaa** [comment]
3 months have passed @BertHartm, if you'd like some effort put by others towards your issue then posting an example of how to repro would go a long way.
