### ISSUE TITLE
proxy server doesn't receive the post params.

### ISSUE THREAD

**Issue by icepoint0** [hapijs/h2o2#72]
when i set hapijs's request proxy the request to my proxy server,my proxy server never receive the params ,why ?

here is the code

>   server.route({
>     method: ['GET','PUT','POST','DELETE'],
>     path: '/atyun/{any*}',
>     handler: {
>       proxy: {
>         host: '127.0.0.1',
>         port: '3000',
>         protocol: 'http'
>       }
>     }
>   });

**Comment by spanditcaa** [comment]
I'm unable to reproduce this.  If I run two hapi 16 servers, one with your route and the other with 

````
{
  method: '*',
  path: '/{p*}',
  handler: function(request, reply) {
    return reply({path: request.path, query: request.query})
  }
````
The response from a proxied request to ````/atyun/doesThisWork?work=true```` is:
````
{
"path": "/atyun/doesThisWork",
"query": {
"work": "true"
}
````

Can you provide any additional information about your configuration?

**Comment by icepoint0** [comment]
i have fixed this, Must add the payload config 


```
 server.route({
    method: ['POST', 'PUT'],
    path: '/atyun/{any*}',
    config: {
      payload: {
        output: 'stream',
        parse: false
      },
handle:{
...
}
```
