### ISSUE TITLE
There is no onRequest handler on branch 6.x

### ISSUE THREAD

**Issue by mkozjak** [hapijs/h2o2#74]
Hi,

There is no onRequest handler on branch 6.x like the docs on 6.x say.

**Comment by spanditcaa** [comment]
Hi @mkozjak -- it has been there for two years - https://github.com/hapijs/h2o2/blame/6.x.x/lib/index.js#L187

**Comment by mkozjak** [comment]
@spanditcaa: True! Failed to see there are more 6.x versions pushed to npm.
