### ISSUE TITLE
Batching h2o2 request with bassmaster yields timeout/504

### ISSUE THREAD

**Issue by palmerjc** [hapijs/h2o2#77]
I am using the h2o2 module to proxy calls to an external web service and the individual service works just fine. However, when I try to batch several of these calls together I end up getting a 504 error for each request. Looking for any guidance as to why proxy request might have issues with Bassmaster (https://github.com/hapijs/bassmaster).

**Comment by spanditcaa** [comment]
Hi @palmerjc - hapi 17/latest h2o2 and bassmaster ?

**Comment by palmerjc** [comment]
Hi @spanditcaa - thank you for the prompt reply. 

I am using hapi 17.3.1, h2o2 8.0.1, and bassmaster 3.1.1.  I can provide you my endpoint definitions but can't provide a repo because of security for the service we are proxying.  

This is my non-batch endpoint:

            {
                method: 'GET',
                path: '/license/v3',    
                options: {
                    auth: 'jwt',   
                    validate: {
                        headers: CommonValidation.target_enviornment_schema,
                        query: LicenseValidation.schemas['get.license-v3.query-parameters']
                    },                             
                    pre: [ {method: AuthenticationController.setupAuthHeader, assign: 'setupResult'} ]  
                },                                
                handler: {
                    proxy: {
                        passThrough: true,
                        mapUri: LicenseController.getLicense_v3.mapUri
                    }
                }
            }

This is my batch endpoint:

            {
                method: 'GET',
                path: '/license/v3/batch',
                options: {
                    auth: 'jwt',
                    handler: async function (request, h) {     

                        const payload = 
                        { "requests": [
                            {"method": "GET", "path": "/license/v3", "query": { "serialNumbers": "399-42672768", "includeRelatedAssets": "true" }},
                            {"method": "GET", "path": "/license/v3", "query": { "serialNumbers": "399-42672867", "includeRelatedAssets": "true" }}
                        ] };

                        return (await server.inject({
                            method: 'POST',
                            url: '/batch',
                            headers: request.headers,
                            payload: payload
                        })).result;
                    }   
                }                   
            }

Does this help?

**Comment by spanditcaa** [comment]
Yes @palmerjc - I'll check it out.

**Comment by palmerjc** [comment]
@spanditcaa come across anything yet?

**Comment by spanditcaa** [comment]
@palmerjc I haven't nailed it down yet, but the problem has something to do with setting passThrough:true.  I expect you need headers to pass through for your scenario for authentication.

**Comment by spanditcaa** [comment]
@palmerjc the problem with content-length is resolved with h2o2 8.1.1 -- let me know if your issue continues, there could be another header in your specific case that causes a conflict.

**Comment by palmerjc** [comment]
@spanditcaa - thanks for the update, the batch request seems to go through now but I get garbage back (almost like it isn't honoring my content-type of application/json).  Thoughts as to why this would be?

![image](https://user-images.githubusercontent.com/13563242/39281327-f68b22b6-48d1-11e8-86d7-dffca7403c24.png)

**Comment by palmerjc** [comment]
Another view from the response object showing headers:

![image](https://user-images.githubusercontent.com/13563242/39281803-81b09cde-48d4-11e8-9dfb-c4704a8bd236.png)

**Comment by palmerjc** [comment]
Turns out I need to specify the following request header:

![image](https://user-images.githubusercontent.com/13563242/39281992-877f1d06-48d5-11e8-8a9a-d294e79da7bd.png)

Don't seem to have to do this for regular calls to the single (non-batch) endpoint.

Thanks again for the fix you put in, it is a big help to be able to run these requests as a batch.

**Comment by spanditcaa** [comment]
That is interesting @palmerjc.. take a look at the accept-encoding that is being sent by the bassmaster request.  I'm curious if nothing is being passed so your final endpoint is defaulting to its native SOAP with some encoding, where the proxy route with passthrough is passing along a more specific browser accept-encoding which includes application/json.

**Comment by palmerjc** [comment]
The request coming into '/license/v3/batch' endpoint has gzip Accept-Encoding (which is odd) because calling the single endpoint the Accept-Encoding (inspected in the mapURI method) shows application/json.

**Comment by spanditcaa** [comment]
You've found a puzzle.  I don't see 'gzip' in h2o2 or bassmaster.

@palmerjc cc:@cadecairos if you all want to dig further I'm always in for a puzzle, otherwise it looks like your use case is resolved and we can leave this closed.

**Comment by cadecairos** [comment]
I wonder if this has something to do with how Bassmaster injects requests. I don't have the time today to investigate, but if a bug is opened on the bassmaster repo I'll get to it in the future.

**Comment by ggoodman** [comment]
This is breaking non-injected requests. I'm seeing my static assets being truncated.

**Comment by spanditcaa** [comment]
@ggoodman can you provide a failing test ?

**Comment by spanditcaa** [comment]
https://github.com/hapijs/h2o2/issues/78
