### ISSUE TITLE
static assets truncated

### ISSUE THREAD

**Issue by spanditcaa** [hapijs/h2o2#78]

**Comment by ggoodman** [comment]
I've done some local testing and it seems I may have been attempting something that is unsupported by this tool. I was attempting to set a cookie value using hapi's facilities based on the presence of a specific query parameter.

I have not had the chance to look into why this was resulting in static assets appearing to be truncated but I don't think that `8.1.1` introduced this issue.

**Comment by spanditcaa** [comment]
Feel free to reopen if you still experience this with 8.1.1.  I'm assuming the scenario above and haven't been able to reproduce the issue with the latest h2o2.  Modifying the proxied request without modifying a content-length header would yield truncated payloads and seems the likely cause of your issue.  This is no longer possible in h2o2 using passthrough as we are removing content-length header.
