### ISSUE TITLE
Call an external API and then continue with processing

### ISSUE THREAD

**Issue by karanmartian** [hapijs/h2o2#80]
Hi,
Can this be used such that in the handler i call an external api and continue in the handler without waiting for a response from that external api. Basically just want to dump some data through an external api without having the handler wait for any response

**Comment by spanditcaa** [comment]
H2O2 is designed specifically for reverse proxy scenarios.  If you just want to call an external API from a handler and discard the response, take a look at https://github.com/hapijs/wreck.
