### ISSUE TITLE
Can't proxy options requests

### ISSUE THREAD

**Issue by nlemoing** [hapijs/h2o2#83]
h2o2 is unable to proxy any requests with method "OPTIONS"

Steps to reproduce:

Register a route with the following settings:
```
method: 'OPTIONS',
path: '/test',
handler: function (request, h) {
  return h.proxy({
    host: 'http://google.com'
  });
}
```
Run the server and make an "OPTIONS" request to the path specified. 
Receive the error message:
`AssertionError [ERR_ASSERTION]: Cannot proxy if payload is parsed or if output is not stream or data
    at Object.internals.handler (/var/bonfire-api/node_modules/h2o2/lib/index.js:78:10)`
It seems like Hapi automatically sets the payload for OPTIONS requests to
```
{
  output: 'data',
  parse: true
}
```
Is it possible to handle OPTIONS routes as a separate case?

**Comment by nlemoing** [comment]
As a follow up to this, Hapi will handle pre-flight `OPTIONS` requests as part of `CORS` if you don't specify a handler for it. The catch with this is that you have to specify the `additionalHeaders` field yourself. 
One solution I found to this problem was to use Wreck to manually proxy `OPTIONS` requests, bypassing h2o2 entirely. However, I think it would be beneficial for h2o2 to add support for `OPTIONS` requests for those making proxy requests from the browser.

**Comment by hueniverse** [comment]
@spanditcaa are you planning to address this issue?

**Comment by spanditcaa** [comment]
Yes @hueniverse - I'll have time next week, or @nlemoing we'd certainly take a PR for this issue.

**Comment by hueniverse** [comment]
Setting route options `payload: { parse: false }` should fix it.
