### ISSUE TITLE
feature request: upstreamPassThrough only 

### ISSUE THREAD

**Issue by cdaringe** [hapijs/h2o2#87]
# problem

`passThrough` passes through bi-directionly.  `localPassThrough` passes state from local => upstream.  i need the inverse of `localPassThrough`

# discussion

is something you'd be willing to support?

perhaps the API could be simplified to `passThrough = 'downstream' | 'upstream' | 'bidirectional'` or something similar?

**Comment by spanditcaa** [comment]
I'm open to it.  @hueniverse you wrote the original passthrough vs. localstatepassthrough in 2014 -- any input as to why they are treated separately ?

**Comment by spanditcaa** [comment]
@cdaringe care to put together a PR ?  We'd deprecate localstatepassthrough so this would be a semver major change.  I prefer ```` passThrough:  {downstream: true, upstream: true} ```` 

vs. strings

**Comment by jackbravo** [comment]
@cdaringe could you provide a test case or example of how you expect this to work?

**Comment by cdaringe** [comment]
hey guys.  want to contribute, but overcommitted.  i moved on from this.  feel free to close.  will reopen if i find the time/motivation to pursue further

**Comment by jackbravo** [comment]
I ask because if you see PR #91, you can see there are no tests covering this setting.

**Comment by spanditcaa** [comment]
per above, closing.
