### ISSUE TITLE
Call settings.mapUri with `h` as the second argument

### ISSUE THREAD

**Issue by tsantef** [hapijs/h2o2#89]
I have a use case where mapUri cannot be completed and need to call `h.unstate` from my mapUri handler. Would it be possible to pass in `h` along with the request? I tried this by editing the file in node_modules and it worked perfectly for my needs. 

https://github.com/hapijs/h2o2/blob/905e5273c6aca184a663368390ba5bb2ed05bc10/lib/index.js#L87

For symmetry, I would also include h to calls to onRequest and onResponse.

**Comment by kanongil** [comment]
That seems inappropriate. A map function should not have side-effects, and the other features of `h` does not make sense in that context.

**Comment by tsantef** [comment]
@kanongil that's a fair point about mapUri. I'll see if I can do what I need with the route's `pre` option.
