### ISSUE TITLE
Proxy WebSocket protocol

### ISSUE THREAD

**Issue by Rainson12** [hapijs/h2o2#90]
I am currently using HAPI with the plugin 'hapi-plugin-websocket' to be able to serve websockets. The serving of the websocket requests will be done in microservice other than the main public api therefore i need to proxy the ws requests from the public api to the websocket api but it seems like h2o2 is currently only able to serve http/https requests. Is there any chance to extend the proxy forwarding to ws:// protocol?

**Comment by spanditcaa** [comment]
Happy to take a PR @Rainson12

**Comment by hueniverse** [comment]
This is beyond the scope of this module.
