### ISSUE TITLE
Provide option to allow for a custom http-client that abides by the Wreck interface

### ISSUE THREAD

**Issue by tuckbick** [hapijs/h2o2#92]
The large enterprise company that I work for currently uses an http-client that wraps Wreck. Our wrapper allows us to extend the functionality of Wreck (metric collection, authentication, tracing, etc).

Proposal: In order to use `h2o2` with our wrapped version of `Wreck`, enable `h2o2` to accept an `httpClient` option. The value/library passed to this option would have to abide by the same interface that Wreck provides. If not provided, simply fallback to use `Wreck`.

So, before I go down the route of creating a PR to add the feature, is this idea even something that has a chance of being merged in?

**Comment by spanditcaa** [comment]
Sure @tuckbick - please prepare a PR including updated docs requiring the wreck interface.  Are you on hapi 17+ only or will there be a 16.x and 17+ version?

**Comment by tuckbick** [comment]
Excellent! Thank you for the quick feedback. Within our organization we're only supporting hapi 17+.
